spring:
  application:
    name: word-test-system

  datasource:
    url: jdbc:mysql://localhost:3306/word_test?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: Wxy20051126.
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      force: true
